#!/bin/zsh

echo "Start initialization..."

DEFAULT_NAME="Untitled"
CURRENT=$(cd $(dirname $0);pwd)
DIR_NAME=`echo "$CURRENT" | sed -e 's/.*\/\([^\/]*\)$/\1/'`

EXTENSIONS=(".pro" ".sch" ".kicad_pcb")

for EXTENSION in ${EXTENSIONS[@]}
do
  ORIGIN="$DEFAULT_NAME$EXTENSION"
  UPDATE="$DIR_NAME$EXTENSION"
  echo ORIGIN: $ORIGIN
  echo UPDATE: $UPDATE
  git mv "$ORIGIN" "$UPDATE"
done

git submodule add git@github.com:NJL7502L/kicad.git

echo "DONE!!"
