#!/bin/zsh

echo "########################################################"
echo "\n"
echo "Start initialization..."
echo "\n"

DEFAULT_NAME="Untitled"
CURRENT=$(cd $(dirname $0);pwd)
DIR_NAME=`echo "$CURRENT" | sed -e 's/.*\/\([^\/]*\)$/\1/'`

EXTENSIONS=(".pro" ".sch" ".kicad_pcb")
echo "--------------------------------------------------------"
echo "1 : Rename Files"
for EXTENSION in ${EXTENSIONS[@]}
do
  ORIGIN="$DEFAULT_NAME$EXTENSION"
  UPDATE="$DIR_NAME$EXTENSION"
  echo "\t" ORIGIN: $ORIGIN
  echo "\t" UPDATE: $UPDATE
  git mv "$ORIGIN" "$UPDATE"
done

if test $# -lt 1 || test 'no-push' != $1 ;then
  git add .
  git commit -m 'zsh init: rename files'
fi

echo "\n"
echo "--------------------------------------------------------"
echo "2 : Git Submodule add Kicad"
git submodule add -f  git@github.com:NJL7502L/kicad.git

if test $# -lt 1 || test 'no-push' != $1 ;then
  git add .
  git commit -m 'zsh init: add submodule kicad'
fi
echo "\n"
echo "--------------------------------------------------------"
echo "3 : Git Submodule add Digikey"
git submodule add -f git@github.com:Digi-Key/digikey-kicad-library.git

if test $# -lt 1 || test 'no-push' != $1 ;then
  git add .
  git commit -m 'zsh init: add submodule digikey'
fi
echo "\n"

if test $# -lt 1 || test 'no-push' != $1 ;then
  echo "--------------------------------------------------------"
  echo "4 : Git push"

  git push origin master
  echo "\n"
fi
echo "--------------------------------------------------------"
echo "5 : mkdir gbr dsn"

mkdir gbr
mkdir dsn
echo "\n"
echo "--------------------------------------------------------"
echo "DONE!!"
echo "########################################################"
